export const colors = [
  { hex: "#91A6FF", name: "Cornflower Blue" },
  { hex: "#FF88DC", name: "Persian Pink" },
  { hex: "#80FF72", name: "Screamin Green" },
  { hex: "#FF5154", name: "Tart Orange" },
  { hex: "#F2C4DE", name: "Cotton Candy" },
  { hex: "#71B1D9", name: "Robin Egg Blue" },
  { hex: "#AED8F2", name: "Baby Blue" },
  { hex: "#F2DEA2", name: "Cornflower Yellow" },
  { hex: "#F2CDC4", name: "Dusty Pink" },
  { hex: "#ABD3DB", name: "Dusty Blue" },
  { hex: "#C2E6DF", name: "Seafoam" },
  { hex: "#D1EBD8", name: "Pastel Green" },
  { hex: "#E5F5DC", name: "Pale Green" },
  { hex: "#FFFFE", name: "Cornsilk" },
  { hex: "#F2D0D9", name: "Blush" },
  { hex: "#F2F2F2", name: "Cloud Grey" },
  { hex: "#8596A6", name: "Denim Blue" },
  { hex: "#F2D9D0", name: "Light Salmon" },
  { hex: "#A9B5D9", name: "Slate Blue" },
  { hex: "#F2A477", name: "Clementine" },
  { hex: "#F29472", name: "Red Orange" },
  { hex: "#F2C4C4", name: "Baby Pink" },
  { hex: "#F2F2F2", name: "Light Silver" },
  { hex: "#5F9595", name: "Sea Green" },
  { hex: "#F0BC68", name: "Sun Orange" },
  { hex: "#C4D7D1", name: "Pastel Teal" },
  { hex: "#F5D1C3", name: "Pastel Pink" },
  { hex: "#FFB6A3", name: "Salmon" },
];
